type PdfSection = {
  title: string
  lines: string[]
}

export async function exportStudentToolPdf(title: string, sections: PdfSection[]) {
  const { default: jsPDF } = await import("jspdf")
  const doc = new jsPDF()
  const margin = 16
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  let y = 20

  doc.setFont("helvetica", "bold")
  doc.setFontSize(18)
  doc.text(title, margin, y)
  y += 10

  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.text(`Generated by UniChase on ${new Date().toLocaleDateString()}`, margin, y)
  y += 12

  sections.forEach((section) => {
    if (y > pageHeight - 30) {
      doc.addPage()
      y = 20
    }

    doc.setFont("helvetica", "bold")
    doc.setFontSize(13)
    doc.text(section.title, margin, y)
    y += 7

    doc.setFont("helvetica", "normal")
    doc.setFontSize(10)

    section.lines.forEach((line) => {
      const wrapped = doc.splitTextToSize(line, pageWidth - margin * 2)
      wrapped.forEach((part: string) => {
        if (y > pageHeight - 18) {
          doc.addPage()
          y = 20
        }

        doc.text(part, margin, y)
        y += 6
      })
    })

    y += 5
  })

  doc.save(`${title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "unichase"}.pdf`)
}
